name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects:
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: System OS and version
      description: What OS are you running and what version is it?
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version of pysimplecli
      description: What version of our software are you running?
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version of Python
      description: What version of Python you running? (`python -V`)
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Relevant example
      description: Please provide a clear and concise example of the bug.
      render: python
    validations:
      required: true
